### ISSUE TITLE
xdg-open support?

### ISSUE THREAD

**Issue by postsolar** [nix-community/nix-snapd#8]
Thank you for working on this flake! I have an issue with `xdg-open` not working, or at least I suspect it's the cause. I was trying to use [transitionsdj](https://snapcraft.io/transitionsdj), but can't connect my soundcloud account because the browser wouldn't open. The error I'm getting is
```log
user-open error: cannot open supplied URL
```

I believe the cause is that it uses `xdg-open` under the hood.
Verifying it manually:
```console
$ snap run --shell transitionsdj
bash-5.0$ xdg-open https://google.com
user-open error: cannot open supplied URL
```

It works fine outside of the snap.

**Comment by io12** [comment]
This should be fixed after https://github.com/io12/nix-snapd/commit/d87a58cc9880bf81560d7a2b7be3635ed7e71866. Let me know if it works now. Thanks!

**Comment by postsolar** [comment]
Doesn't seem to be helping. I've done:
- Update the flake input
- Rebuild
- `sudo systemctl daemon-reload; sudo systemctl restart snapd.service`
- Manually delete everything that seems to be related to snap from the file system
- Reinstall the snaps (they seem to still be installing from cache for some reason)

But `xdg-open <url>` still doesn't work. Maybe something else is required to properly update?

**Comment by io12** [comment]
Have you tried rebooting?

**Comment by postsolar** [comment]
Yep, still no effect. Just for clarity, does it work for you with these commands?
```console
$ sudo snap install hello-world
$ snap run --shell hello-world
$ xdg-open https://google.com
```

**Comment by io12** [comment]
> Just for clarity, does it work for you with these commands?

Yes, with Firefox in `environment.systemPackages` it runs Firefox. I'm building your [config](https://github.com/postsolar/config/) now to see if I can reproduce the issue.

**Comment by io12** [comment]
I couldn't reproduce the issue with your config. Running those commands opened google.com in firefox-developer-edition. I did have to replace hyprland with GNOME, because there was an error with hyprland.

```
error: hash mismatch in fixed-output derivation '/nix/store/qj0acgvhk1gdipfvsdiqskn86hv8s2ry-focus-by-keyboard...outfoxxed-3Ahy3-3Amaster.patch.drv':
         specified: sha256-JtgdilIZLLGFlw9ROCD6uoUd7KBa9HWDBmzrouP06p0=
            got:    sha256-4aQKB4fhfmK/fYXZtrzXZ4blnhZD8S8SczNdS1+GkbM=
```

After changing the hash, the patch fails to apply.

**Comment by io12** [comment]
I'm going to close this now. Feel free to re-open the issue if you're still having this problem.
